### ISSUE TITLE
Upgrade the version of Go to 1.18 or 1.19

### ISSUE THREAD

**Issue by abhioncbr** [startreedata/pinot-client-go#11]
Currently, the Go version is `1.13` which is almost three years old and also there is a [vulnerability](https://github.com/advisories/GHSA-69cg-p879-7622) mentioned in the old version.

**Comment by abhioncbr** [comment]
Please assign it to me. Thanks.

**Comment by abhioncbr** [comment]
We merged the branch https://github.com/startreedata/pinot-client-go/pull/12. 
Closing the issue.

**Comment by xiangfu0** [comment]
Many thanks for your contribution!
