### ISSUE TITLE
Use different active Go Zookeeper package instead of currently used. 

### ISSUE THREAD

**Issue by abhioncbr** [startreedata/pinot-client-go#15]
**Problem**
- Currently, we are using the `samuel/go-zookeeper` Go package; however, the package has been archived from mid-2021, and the forked repo is also dormant.  It would be better to use the active zookeeper package.

**Proposed Solution**
Here are some of the other zookeeper packages
- https://pkg.go.dev/github.com/prometheus/prometheus
- https://pkg.go.dev/github.com/hashicorp/vault/physical/zookeeper

This issue is to finalize the library and using the new one.

**Comment by abhioncbr** [comment]
Please assign the ticket to me.

**Comment by xiangfu0** [comment]
Thanks for reporting and picking this up!

**Comment by abhioncbr** [comment]
Both the above-mentioned packages are using `github.com/go-zookeeper/zk`.

**Comment by abhioncbr** [comment]
We can close this issue. Thanks
