### ISSUE TITLE
Create CI pipeline

### ISSUE THREAD

**Issue by xiangfu0** [startreedata/pinot-client-go#6]
Should follow python client lib to create a CI including all the unit test and integration test by launching a pinot quickstart in docker, then query.

https://github.com/python-pinot-dbapi/pinot-dbapi

**Comment by zaheersyedkdr** [comment]
I am interested to pick this, if it is open. Let me know if anyone is already working on this

**Comment by xiangfu0** [comment]
Please! Thanks! 🙏

**Comment by xiangfu0** [comment]
Done by #16
